### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by sardelisp** [Magisk-Modules-Repo/adreno-630-gpu-driver#1]
Magisk manager does not pass safety net.
Stories in Instagram shows black screen.

**Comment by P1N2O** [comment]
@sardelisp Has nothing to do with Magisk Manager / SafetyNet.
Also, details like, Device, Android Version, ROM, etc would be helpful..

Any other bugs other than Blackedout images in Instagram? Any screen flickering, video playback problems?

**Comment by sardelisp** [comment]
Sorry friend just sign up on this..
I have OnePlus 6t latest stock ROM 9.0.17 version 9 pie
YouTube videos and Facebook videos plays well..
Didn't notice any other problems..
Investigating

**Comment by P1N2O** [comment]
> Sorry friend just sign up on this..
> I have OnePlus 6t latest stock ROM 9.0.17 version 9 pie
> YouTube videos and Facebook videos plays well..
> Didn't notice any other problems..
> Investigating

Pie ROM's seem to have problems with the latest GPU Drivers (v4xx).

I'm making it install able only on Android 10 devices in the next update.

Kindly uninstall the module if you are on Pie and have major problems, I'll see if I can fix this for Pie BTW.
