### ISSUE TITLE
Power button option broken

### ISSUE THREAD

**Issue by raphson93** [Magisk-Modules-Repo/adreno-630-gpu-driver#2]
I flashed the latest module on mi8 with miui 10.3.5 + sphinx 3.1
The drag down notifications and long press power button gave me black screen

**Comment by amirkitsune** [comment]
> I flashed the latest module on mi8 with miui 10.3.5 + sphinx 3.1
> The drag down notifications and long press power button gave me black screen

If not mistake, MIUI 10.3.5 on Mi 8 is Android 9.0 Pie right?

But this module is for Android 10.

**Comment by raphson93** [comment]
Ya sir, is Android 9.0.
so the latest module only target for 10 and above?

**Comment by amirkitsune** [comment]
> Ya sir, is Android 9.0.
> so the latest module only target for 10 and above?

I think we have to wait developer answer your question. because what i read on commit, it mention Android 10.

**Comment by P1N2O** [comment]
> Ya sir, is Android 9.0.
> so the latest module only target for 10 and above?

The newer version (v415) of the GPU Driver is known to have some problems with Android 9. But tested and works fine on Android 10. So I've restricted the module to only install on SDM845 devices with Android 10.

Edit: Kindly uninstall the module if you are not on Android 10.

Thanks for reporting BTW!
