### ISSUE TITLE
No display on poco f1

### ISSUE THREAD

**Issue by ethanjjjjjjj** [Magisk-Modules-Repo/adreno-630-gpu-driver#3]
I installed this on my poco f1, after rebooting I had no display, deleted the module in /data/adb/modules with twrp but still have no display

**Comment by P1N2O** [comment]
> I installed this on my poco f1, after rebooting I had no display, deleted the module in /data/adb/modules with twrp but still have no display

Uninstall Magisk via Magisk Uninstaller..
Seems like it's causing problems on stock ROM.
